[project]
name = "sync-distributor"
authors = ["Sync Distributor Team"]
description = "Decentralized Transaction Synchronization and Escrow Platform"
telemetry = false
requirements = []
[contracts.sync_distributor]
path = "contracts/sync_distributor.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
